import React, { useMemo, useState } from 'react';
import { History, Search, ArrowDownLeft, ArrowUpRight } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useData } from '../context/DataContext';

export const ActivityPage = () => {
  const { settings } = useAuth(); const { transactions } = useData(); const [query, setQuery] = useState(''); const [status, setStatus] = useState('all');
  const rows = useMemo(() => transactions.filter((tx) => (status === 'all' || tx.status === status) && (!query || tx.customerName.toLocaleLowerCase('ar').includes(query.toLocaleLowerCase('ar')) || tx.createdBy?.toLocaleLowerCase('ar').includes(query.toLocaleLowerCase('ar')))), [transactions, query, status]);
  const statusLabel = { approved: 'معتمد', pending: 'بانتظار الموافقة', rejected: 'مرفوض' };
  return <div className="max-w-6xl mx-auto space-y-6 animate-in fade-in duration-200"><header className="pb-4 border-b border-slate-800"><h2 className="text-xl sm:text-2xl font-black text-white flex items-center gap-2"><History className="w-6 h-6 text-teal-400" />كل التحركات المالية</h2><p className="text-xs sm:text-sm text-slate-400 mt-1">سجل كامل للديون والتسديدات والطلبات المعلقة.</p></header><section className="glass-panel rounded-3xl p-5 sm:p-6 border border-slate-800"><div className="flex flex-col sm:flex-row gap-3 mb-5"><div className="relative flex-1"><Search className="absolute right-3 top-2.5 w-4 h-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="بحث باسم الزبون أو العامل..." className="w-full pr-9 pl-3 py-2.5 rounded-xl glass-input text-xs" /></div><select value={status} onChange={(e) => setStatus(e.target.value)} className="px-3 py-2.5 rounded-xl glass-input text-xs"><option value="all">كل الحالات</option><option value="approved">معتمد</option><option value="pending">بانتظار الموافقة</option><option value="rejected">مرفوض</option></select></div><p className="text-[11px] text-slate-400 mb-3">{rows.length} حركة مطابقة</p><div className="space-y-2 max-h-[620px] overflow-y-auto">{rows.length ? rows.map((tx) => { const debt = tx.type === 'debt'; return <article key={tx.id} className="p-4 rounded-2xl bg-slate-900/60 border border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div className="flex items-center gap-3"><div className={`p-2 rounded-xl ${debt ? 'bg-rose-500/10 text-rose-400' : 'bg-emerald-500/10 text-emerald-400'}`}>{debt ? <ArrowDownLeft className="w-5 h-5" /> : <ArrowUpRight className="w-5 h-5" />}</div><div><h3 className="text-sm font-bold text-white">{tx.customerName}</h3><p className="text-[11px] text-slate-400 mt-1">{debt ? 'دين' : 'تسديد'} · بواسطة {tx.createdBy} · {tx.date}</p><p className="text-[11px] text-slate-500 mt-1">{tx.details || 'لا توجد تفاصيل إضافية'}</p></div></div><div className="sm:text-left"><strong className={debt ? 'text-rose-400' : 'text-emerald-400'}>{tx.amount.toLocaleString()} {settings.currency}</strong><span className={`block mt-1 text-[10px] font-bold ${tx.status === 'approved' ? 'text-emerald-400' : tx.status === 'pending' ? 'text-amber-400' : 'text-rose-400'}`}>{statusLabel[tx.status]}</span></div></article>; }) : <p className="py-16 text-center text-xs text-slate-500">لا توجد حركات مطابقة.</p>}</div></section></div>;
};
